/**
 * Runtime entry for the `whatsapp-rust-bridge/proto-types` sub-export.
 *
 * The companion `proto-types.d.ts` (auto-generated by
 * `scripts/gen-protobufjs-dts.ts`) declares the protobufjs-style namespace
 * `proto`, providing both the `interface I<Name>` and `class <Name>` protobufjs
 * shapes. TypeScript prefers the `.d.ts` over this
 * `.ts` for typing — what consumers `import { proto }` get is typed by the
 * generated declarations, while the runtime values come from `proto-namespace`
 * (which assembles the namespace from ts-proto's exports).
 */

export { proto } from './proto-namespace'
