/**
 * Regenerate the pure-TypeScript protobuf codec from the exact `waproto`
 * package selected by Cargo.lock.
 *
 * Resolving the schema through Cargo metadata keeps the bridge tied to its
 * single public `whatsapp-rust` dependency without a sibling-repository path
 * or a second independently versioned copy of whatsapp.proto.
 */

import { fromBinary } from '@bufbuild/protobuf'
import {
	FieldDescriptorProto_Label as Label,
	FieldDescriptorProto_Type as Type,
	FileDescriptorSetSchema,
	type DescriptorProto,
	type FieldDescriptorProto
} from '@bufbuild/protobuf/wkt'
import { mkdirSync, readFileSync, renameSync, rmSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const OUTPUT_DIR = join(ROOT, 'ts', 'generated')
const OUTPUT_FILE = join(OUTPUT_DIR, 'whatsapp.ts')
const SURFACE_FILE = join(OUTPUT_DIR, 'whatsapp-surface.txt')
const PROTO_PACKAGE_NAME = 'waproto'
const PROTO_SOURCE_PATH = ['src', 'whatsapp.proto'] as const
const TS_PROTO_PLUGIN = join(ROOT, 'node_modules', '.bin', 'protoc-gen-ts_proto')
const GENERATED_WIRE_IMPORT = 'import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";'
const OPTIMIZED_WIRE_IMPORT = 'import { BinaryReader, BinaryWriter } from "../proto-reader";'
const GENERATED_LONG_PARAMETER = 'function longToNumber(int64: { toString(): string }): number {'
const OPTIMIZED_LONG_PARAMETER = 'function longToNumber(int64: number | { toString(): string }): number {'
const GENERATED_LONG_CONVERSION = 'const num = globalThis.Number(int64.toString());'
const OPTIMIZED_LONG_CONVERSION =
	'const num = typeof int64 === "number" ? int64 : globalThis.Number(int64.toString());'
const SAFE_NUMBER_READER_METHODS = ['uint64', 'int64', 'sint64', 'fixed64', 'sfixed64'] as const

const TS_PROTO_OPTIONS = [
	'outputJsonMethods=false',
	'useExactTypes=false',
	'useOptionals=all',
	'noDefaultsForOptionals=true',
	'initializeFieldsAsUndefined=false'
] as const

// Protobuf keyword per descriptor type, so the manifest reads like the .proto
// it came from rather than like a descriptor dump.
const TYPE_KEYWORD: Partial<Record<Type, string>> = {
	[Type.DOUBLE]: 'double',
	[Type.FLOAT]: 'float',
	[Type.INT64]: 'int64',
	[Type.UINT64]: 'uint64',
	[Type.INT32]: 'int32',
	[Type.FIXED64]: 'fixed64',
	[Type.FIXED32]: 'fixed32',
	[Type.BOOL]: 'bool',
	[Type.STRING]: 'string',
	[Type.MESSAGE]: 'message',
	[Type.BYTES]: 'bytes',
	[Type.UINT32]: 'uint32',
	[Type.ENUM]: 'enum',
	[Type.SFIXED32]: 'sfixed32',
	[Type.SFIXED64]: 'sfixed64',
	[Type.SINT32]: 'sint32',
	[Type.SINT64]: 'sint64'
}

const HEADER = [
	'# Generated by scripts/gen-ts-proto.ts from waproto/src/whatsapp.proto. Do not edit.',
	'# <message>\t<field>\t<number>\t<label>\t<type>[\t<enum head or message type>]',
	'# <label> is optional | required | repeated | repeated packed | map.',
	'# A line with only <message> is a message the schema declares with no fields.',
	''
].join('\n')

const LABEL_KEYWORD: Partial<Record<Label, string>> = {
	[Label.OPTIONAL]: 'optional',
	[Label.REQUIRED]: 'required',
	[Label.REPEATED]: 'repeated'
}

interface CargoPackage {
	name: string
	manifest_path: string
}

interface CargoMetadata {
	packages: CargoPackage[]
}

const run = (command: readonly string[], stdout: 'pipe' | 'inherit' = 'inherit'): Uint8Array => {
	const result = Bun.spawnSync({ cmd: [...command], cwd: ROOT, stdout, stderr: 'inherit' })
	if (result.exitCode !== 0) {
		throw new Error(`${command[0]} exited with status ${result.exitCode}`)
	}
	return result.stdout
}

const replaceGeneratedContract = (source: string, expected: string, replacement: string): string => {
	const first = source.indexOf(expected)
	if (first < 0 || first !== source.lastIndexOf(expected)) {
		throw new Error(`ts-proto output must contain exactly one occurrence of: ${expected}`)
	}
	return source.replace(expected, replacement)
}

/**
 * Flatten the compiled schema into one tab-separated line per field:
 *
 *   <message path>  <declared name>  <number>  <label>  <type>  [type ref]
 *
 * `tests/proto-schema-surface.test.ts` replays this against the generated
 * codec, so the schema — not the generator's own output — is what says which
 * fields must cross, under which name, at which number. Keeping it as text
 * rather than a descriptor blob also puts an upstream renumbering in the diff.
 */
const buildSurface = (descriptor: Uint8Array): string => {
	const set = fromBinary(FileDescriptorSetSchema, descriptor)
	const mapEntries = new Map<string, DescriptorProto>()
	const enumHeads = new Map<string, number>()
	const lines: string[] = []

	const index = (scope: string, message: DescriptorProto): void => {
		const path = `${scope}.${message.name}`
		if (message.options?.mapEntry) mapEntries.set(path, message)
		for (const declared of message.enumType) {
			enumHeads.set(`${path}.${declared.name}`, declared.value[0]?.number ?? 0)
		}
		for (const nested of message.nestedType) index(path, nested)
	}

	const typeRef = (field: FieldDescriptorProto, local: (p: string) => string): string => {
		if (field.type === Type.ENUM) {
			// No fallback: a proto2 enum need not start at zero, and defaulting an
			// unresolved reference to 0 would hand the test a value the schema
			// never declares.
			const head = enumHeads.get(field.typeName)
			if (head === undefined) throw new Error(`unresolved enum ${field.typeName} on ${field.name}`)
			return `${local(field.typeName)}=${head}`
		}
		if (field.type === Type.MESSAGE) return local(field.typeName)
		return ''
	}

	const describe = (field: FieldDescriptorProto, local: (p: string) => string): [string, string, string] => {
		const entry = field.type === Type.MESSAGE ? mapEntries.get(field.typeName) : undefined
		if (!entry) {
			const label = LABEL_KEYWORD[field.label]
			if (!label) throw new Error(`unhandled label on ${field.name}`)
			const keyword = TYPE_KEYWORD[field.type]
			if (!keyword) throw new Error(`unhandled type on ${field.name}`)
			// Packedness decides the wire type of a repeated scalar, and proto2
			// defaults to unpacked, so it has to be recorded rather than inferred.
			const packed = field.label === Label.REPEATED && field.options?.packed === true
			return [packed ? `${label} packed` : label, keyword, typeRef(field, local)]
		}
		const key = entry.field.find(candidate => candidate.number === 1)!
		const value = entry.field.find(candidate => candidate.number === 2)!
		return ['map', `map<${TYPE_KEYWORD[key.type]},${TYPE_KEYWORD[value.type]}>`, typeRef(value, local)]
	}

	const emit = (scope: string, local: (p: string) => string, message: DescriptorProto): void => {
		const path = `${scope}.${message.name}`
		if (message.options?.mapEntry) return
		// A message with no fields still has a generated type to resolve, so it
		// gets a line of its own rather than being inferred from its fields.
		if (message.field.length === 0) lines.push(local(path))
		for (const field of message.field) {
			const [label, keyword, ref] = describe(field, local)
			const columns = [local(path), field.name, String(field.number), label, keyword]
			if (ref) columns.push(ref)
			lines.push(columns.join('\t'))
		}
		for (const nested of message.nestedType) emit(path, local, nested)
	}

	for (const file of set.file) {
		const root = `.${file.package}`
		for (const declared of file.enumType) enumHeads.set(`${root}.${declared.name}`, declared.value[0]?.number ?? 0)
		for (const message of file.messageType) index(root, message)
	}
	for (const file of set.file) {
		const root = `.${file.package}`
		const local = (path: string): string => (path.startsWith(`${root}.`) ? path.slice(root.length + 1) : path)
		for (const message of file.messageType) emit(root, local, message)
	}

	return `${HEADER}${lines.join('\n')}\n`
}

const metadata = JSON.parse(
	new TextDecoder().decode(run(['cargo', 'metadata', '--format-version', '1', '--locked'], 'pipe'))
) as CargoMetadata
const protoPackages = metadata.packages.filter(pkg => pkg.name === PROTO_PACKAGE_NAME)

if (protoPackages.length !== 1) {
	throw new Error(`expected one resolved ${PROTO_PACKAGE_NAME} package, found ${protoPackages.length}`)
}

const manifestDir = dirname(protoPackages[0]!.manifest_path)
const protoFile = join(manifestDir, ...PROTO_SOURCE_PATH)
const protoDir = dirname(protoFile)
const tempDir = join(OUTPUT_DIR, `.ts-proto-${process.pid}`)

mkdirSync(tempDir, { recursive: false })
try {
	const descriptorFile = join(tempDir, 'whatsapp.desc')
	run([
		'protoc',
		`--proto_path=${protoDir}`,
		`--plugin=protoc-gen-ts_proto=${TS_PROTO_PLUGIN}`,
		`--ts_proto_out=${tempDir}`,
		`--ts_proto_opt=${TS_PROTO_OPTIONS.join(',')}`,
		`--descriptor_set_out=${descriptorFile}`,
		protoFile
	])
	const generatedFile = join(tempDir, 'whatsapp.ts')
	let generatedSource = readFileSync(generatedFile, 'utf8')
	generatedSource = replaceGeneratedContract(generatedSource, GENERATED_WIRE_IMPORT, OPTIMIZED_WIRE_IMPORT)
	generatedSource = replaceGeneratedContract(generatedSource, GENERATED_LONG_PARAMETER, OPTIMIZED_LONG_PARAMETER)
	generatedSource = replaceGeneratedContract(generatedSource, GENERATED_LONG_CONVERSION, OPTIMIZED_LONG_CONVERSION)
	for (const method of SAFE_NUMBER_READER_METHODS) {
		generatedSource = generatedSource.replaceAll(
			`longToNumber(reader.${method}())`,
			`reader.${method}Number()`
		)
	}
	if (generatedSource.includes('longToNumber(reader.')) {
		throw new Error('ts-proto added an int64 reader method without a safe-number specialization')
	}
	writeFileSync(generatedFile, generatedSource)
	writeFileSync(SURFACE_FILE, buildSurface(readFileSync(descriptorFile)))
	renameSync(generatedFile, OUTPUT_FILE)
} finally {
	rmSync(tempDir, { recursive: true, force: true })
}

console.log(`Generated ${OUTPUT_FILE} and ${SURFACE_FILE} from ${protoFile}`)
